name: docker-publish

on:
  push:
    branches:
      - main
      - feat/server_impl
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      bake_params:
        description: "Bake params into image (BAKE_PARAMS=1)"
        required: false
        default: "0"
        type: choice
        options: ["0", "1"]

permissions:
  contents: read
  packages: write

env:
  DOCKER_PLATFORMS: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-publish-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # If GHCR_PAT is provided as a repo secret, prefer it; otherwise use GITHUB_TOKEN
      - name: Log in to GHCR (PAT)
        if: secrets.GHCR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Log in to GHCR (GITHUB_TOKEN)
        if: secrets.GHCR_PAT == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Resolve BAKE_PARAMS
        id: bake
        run: |
          if [ -n "${{ inputs.bake_params }}" ]; then
            echo "BAKE_PARAMS=${{ inputs.bake_params }}" >> $GITHUB_OUTPUT
          else
            echo "BAKE_PARAMS=0" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.meta.outputs.created }}
            GH_REPO=${{ github.repository }}
            BAKE_PARAMS=${{ steps.bake.outputs.BAKE_PARAMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
